FROM apache/airflow:2.9.1
ADD requirements.txt .
RUN pip install apache-airflow==${AIRFLOW_VERSION} -r requirements.txt
ENV BASE_DIR="C:\Courses\Data Engineering RD\Data-Engineering-RD\HW_Python\file_storage"
